# List all organizations mentioned in the data

PREFIX rdf:        <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:       <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:        <http://www.w3.org/2002/07/owl#>
PREFIX skos:       <http://www.w3.org/2004/02/skos/core#>
PREFIX dct:        <http://purl.org/dc/terms/>
PREFIX org:        <http://www.w3.org/ns/org#>

SELECT * WHERE {
    ?org a org:Organization .
    OPTIONAL {?org skos:prefLabel ?prefLabel}
    OPTIONAL {?org rdfs:label ?label}
    OPTIONAL {?org dct:description ?description}
    OPTIONAL {?org org:identifier ?identifier}
    OPTIONAL {?org org:classification ?classification}
}
